---
- hosts: mail
#  var: 
  vars_files:
    - config.yml
    - secret.yml
  remote_user: wnoguchi
  become: yes
  tasks:
  - name: install postfix
    yum: name=postfix state=present
  - name: install dovecot
    yum: name=dovecot state=present
  - name: install mariadb-server
    yum: name=mariadb-server state=present
  - name: install dovecot-mysql
    yum: name=dovecot-mysql state=present
    notify:
      - reload dovecot
  - name: install php packages
    yum: name={{item}} state=present
    with_items:
      - php
      - php-fpm
      - php-mysql
      - php-mcrypt
  - name: install epel-release
    yum: name=epel-release state=present
  - name: install nginx
    yum: name=nginx state=present
    notify:
      - reload nginx
      - reload php-fpm

  - copy: src=etc/{{item}} dest=/etc/{{item}} owner=root group=root mode=0644
    with_items:
      - php.ini
      - php-fpm.conf
    notify:
      - reload php-fpm

  - group: name=vusers gid=10000 state=present
  - user: name=vusers comment="Virtual Mail User" uid=10000 group=vusers state=present

  - name: Postfix Configuration
    template: src=etc/postfix/{{item}} dest=/etc/postfix/{{item}} owner=root group=root mode=0644
    with_items:
      - main.cf
      - master.cf
      - mysql_virtual_alias_maps.cf
      - mysql_virtual_domains_maps.cf
      - mysql_virtual_mailbox_limit_maps.cf
      - mysql_virtual_mailbox_maps.cf
    notify:
      - reload postfix
#  - name: Dovecot Configuration
#    template: src=etc/dovecot/{{item}} dest=/etc/dovecot/{{item}} owner=root group=root mode=0644
#    with_items:
#      - 
#    notify:
#      - reload dovecot
  - name: start services
    service: name={{item}} state=started
    with_items:
      - postfix
      - dovecot
      - mariadb
      - nginx
      - php-fpm

  handlers:
#  - name: reload httpd
#    service: name=httpd state=reloaded
  - name: reload postfix
    service: name=postfix state=reloaded
  - name: reload dovecot
    service: name=dovecot state=reloaded
  - name: reload mariadb
    service: name=mariadb state=restart
  - name: reload nginx
    service: name=nginx state=reloaded
  - name: reload php-fpm
    service: name=php-fpm state=reloaded
